// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4ClzjxYolMROgJnLb0OE8Y1sfga2QqA',
    appId: '1:356052316740:web:73634d53c7bc6b3de80211',
    messagingSenderId: '356052316740',
    projectId: 'movieapp-4fb4e',
    authDomain: 'movieapp-4fb4e.firebaseapp.com',
    storageBucket: 'movieapp-4fb4e.firebasestorage.app',
    measurementId: 'G-912VP9NN6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIb-sACBVz_Ix_gwgzrtKxDgyLdtkmiwU',
    appId: '1:356052316740:android:f4ad8b985a9e3bf8e80211',
    messagingSenderId: '356052316740',
    projectId: 'movieapp-4fb4e',
    storageBucket: 'movieapp-4fb4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5cdXXczmdamYodOYlCSmweBBp-9U7ltc',
    appId: '1:356052316740:ios:93f5908e130e880ee80211',
    messagingSenderId: '356052316740',
    projectId: 'movieapp-4fb4e',
    storageBucket: 'movieapp-4fb4e.firebasestorage.app',
    iosClientId: '356052316740-fc6mshbt9e9o790pe603bhrrr69kcm9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5cdXXczmdamYodOYlCSmweBBp-9U7ltc',
    appId: '1:356052316740:ios:93f5908e130e880ee80211',
    messagingSenderId: '356052316740',
    projectId: 'movieapp-4fb4e',
    storageBucket: 'movieapp-4fb4e.firebasestorage.app',
    iosClientId: '356052316740-fc6mshbt9e9o790pe603bhrrr69kcm9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4ClzjxYolMROgJnLb0OE8Y1sfga2QqA',
    appId: '1:356052316740:web:4be52274b907ebcae80211',
    messagingSenderId: '356052316740',
    projectId: 'movieapp-4fb4e',
    authDomain: 'movieapp-4fb4e.firebaseapp.com',
    storageBucket: 'movieapp-4fb4e.firebasestorage.app',
    measurementId: 'G-5RRVEQDETT',
  );
}
